import { Registers, COP0Registers } from "./consts";

export const instructions = {
    ReservedInstruction: (fields, pc) => `---`,
    CopUnusable: (fields, pc) => `COP${fields.cop}\tunusable`,

    LB: (fields, pc) => `lb\t${Registers[fields.rt]}, ${fields.imm16}(${Registers[fields.rs]})`,
    LBU: (fields, pc) => `lbu\t${Registers[fields.rt]}, ${fields.imm16}(${Registers[fields.rs]})`,
    LH: (fields, pc) => `lh\t${Registers[fields.rt]}, ${fields.imm16}(${Registers[fields.rs]})`,
    LHU: (fields, pc) => `lhu\t${Registers[fields.rt]}, ${fields.imm16}(${Registers[fields.rs]})`,
    LW: (fields, pc) => `lw\t${Registers[fields.rt]}, ${fields.imm16}(${Registers[fields.rs]})`,
    SB: (fields, pc) => `sb\t${Registers[fields.rt]}, ${fields.imm16}(${Registers[fields.rs]})`,
    SH: (fields, pc) => `sh\t${Registers[fields.rt]}, ${fields.imm16}(${Registers[fields.rs]})`,
    SW: (fields, pc) => `sw\t${Registers[fields.rt]}, ${fields.imm16}(${Registers[fields.rs]})`,

    LWR: (fields, pc) => `lwr\t${Registers[fields.rt]}, ${fields.imm16}(${Registers[fields.rs]})`,
    LWL: (fields, pc) => `lwl\t${Registers[fields.rt]}, ${fields.imm16}(${Registers[fields.rs]})`,
    SWR: (fields, pc) => `swr\t${Registers[fields.rt]}, ${fields.imm16}(${Registers[fields.rs]})`,
    SWL: (fields, pc) => `swl\t${Registers[fields.rt]}, ${fields.imm16}(${Registers[fields.rs]})`,

    ADD: (fields, pc) => fields.rd ? `add\t${Registers[fields.rd]}, ${Registers[fields.rs]}, ${Registers[fields.rt]}` : "nop",
    ADDU: (fields, pc) => fields.rd ? `addu\t${Registers[fields.rd]}, ${Registers[fields.rs]}, ${Registers[fields.rt]}` : "nop",
    SUB: (fields, pc) => fields.rd ? `sub\t${Registers[fields.rd]}, ${Registers[fields.rs]}, ${Registers[fields.rt]}` : "nop",
    SUBU: (fields, pc) => fields.rd ? `subu\t${Registers[fields.rd]}, ${Registers[fields.rs]}, ${Registers[fields.rt]}` : "nop",
    ADDI: (fields, pc) => fields.rt ? `addi\t${Registers[fields.rt]}, ${Registers[fields.rs]}, ${fields.simm16}` : "nop",
    ADDIU: (fields, pc) => fields.rt ? `addiu\t${Registers[fields.rt]}, ${Registers[fields.rs]}, ${fields.simm16}` : "nop",

    SLT: (fields, pc) => `slt\t${Registers[fields.rd]}, ${Registers[fields.rs]}, ${Registers[fields.rt]}`,
    SLTU: (fields, pc) => `sltu\t${Registers[fields.rd]}, ${Registers[fields.rs]}, ${Registers[fields.rt]}`,
    SLTI: (fields, pc) => `slti\t${Registers[fields.rt]}, ${Registers[fields.rs]}, ${fields.simm16}`,
    SLTIU: (fields, pc) => `sltiu\t${Registers[fields.rt]}, ${Registers[fields.rs]}, $${(fields.simm16 >>> 0).toString(16)}`,

    AND: (fields, pc) => fields.rd ? `and\t${Registers[fields.rd]}, ${Registers[fields.rs]}, ${Registers[fields.rt]}` : "nop",
    OR: (fields, pc) => fields.rd ? `or\t${Registers[fields.rd]}, ${Registers[fields.rs]}, ${Registers[fields.rt]}` : "nop",
    XOR: (fields, pc) => fields.rd ? `xor\t${Registers[fields.rd]}, ${Registers[fields.rs]}, ${Registers[fields.rt]}` : "nop",
    NOR: (fields, pc) => fields.rd ? `nor\t${Registers[fields.rd]}, ${Registers[fields.rs]}, ${Registers[fields.rt]}` : "nop",
    ANDI: (fields, pc) => fields.rt ? `andi\t${Registers[fields.rt]}, ${Registers[fields.rs]}, $${fields.imm16.toString(16)}` : "nop",
    ORI: (fields, pc) => fields.rt ? `ori\t${Registers[fields.rt]}, ${Registers[fields.rs]}, $${fields.imm16.toString(16)}` : "nop",
    XORI: (fields, pc) => fields.rt ? `xori\t${Registers[fields.rt]}, ${Registers[fields.rs]}, $${fields.imm16.toString(16)}` : "nop",

    SLLV: (fields, pc) => fields.rd ? `sllv\t${Registers[fields.rd]}, ${Registers[fields.rs]}, ${Registers[fields.rt]}` : "nop",
    SRLV: (fields, pc) => fields.rd ? `srlv\t${Registers[fields.rd]}, ${Registers[fields.rs]}, ${Registers[fields.rt]}` : "nop",
    SRAV: (fields, pc) => fields.rd ? `srav\t${Registers[fields.rd]}, ${Registers[fields.rs]}, ${Registers[fields.rt]}` : "nop",
    SLL: (fields, pc) => fields.rd ? `sll\t${Registers[fields.rd]}, ${Registers[fields.rt]}, ${fields.shamt}` : "nop",
    SRL: (fields, pc) => fields.rd ? `srl\t${Registers[fields.rd]}, ${Registers[fields.rt]}, ${fields.shamt}` : "nop",
    SRA: (fields, pc) => fields.rd ? `sra\t${Registers[fields.rd]}, ${Registers[fields.rt]}, ${fields.shamt}` : "nop",
    LUI: (fields, pc) => `lui\t${Registers[fields.rt]}, $${fields.imm16.toString(16)}`,

    MULT: (fields, pc) => `mult\t${Registers[fields.rs]}, ${Registers[fields.rt]}`,
    MULTU: (fields, pc) => `multu\t${Registers[fields.rs]}, ${Registers[fields.rt]}`,
    DIV: (fields, pc) => `div\t${Registers[fields.rs]}, ${Registers[fields.rt]}`,
    DIVU: (fields, pc) => `divu\t${Registers[fields.rs]}, ${Registers[fields.rt]}`,
    MFHI: (fields, pc) => `mfhi\t${Registers[fields.rd]}`,
    MFLO: (fields, pc) => `mflo\t${Registers[fields.rd]}`,
    MTHI: (fields, pc) => `mthi\t${Registers[fields.rs]}`,
    MTLO: (fields, pc) => `mtlo\t${Registers[fields.rs]}`,

    J: (fields, pc) => `j\t$${(((pc & 0xF0000000) | (fields.imm26 * 4)) >>> 0).toString(16)}`,
    JAL: (fields, pc) => `jal\t$${(((pc & 0xF0000000) | (fields.imm26 * 4)) >>> 0).toString(16)}`,
    JR: (fields, pc) => `jr\t${Registers[fields.rs]}`,
    JALR: (fields, pc) => `jalr\t${Registers[fields.rd]}, ${Registers[fields.rs]}`,
    BEQ: (fields, pc) => `beq\t${Registers[fields.rs]}, $${((pc + 4) + (fields.simm16 * 4)).toString(16)}`,
    BNE: (fields, pc) => `bne\t${Registers[fields.rs]}, ${Registers[fields.rt]}, $${((pc + 4) + (fields.simm16 * 4)).toString(16)}`,
    BLTZ: (fields, pc) => `bltz\t${Registers[fields.rs]}, $${((pc + 4) + (fields.simm16 * 4)).toString(16)}`,
    BGEZ: (fields, pc) => `bgez\t${Registers[fields.rs]}, $${((pc + 4) + (fields.simm16 * 4)).toString(16)}`,
    BGTZ: (fields, pc) => `bgtz\t${Registers[fields.rs]}, $${((pc + 4) + (fields.simm16 * 4)).toString(16)}`,
    BLEZ: (fields, pc) => `blez\t${Registers[fields.rs]}, $${((pc + 4) + (fields.simm16 * 4)).toString(16)}`,
    BLTZAL: (fields, pc) => `bltzal\t${Registers[fields.rs]}, $${((pc + 4) + (fields.simm16 * 4)).toString(16)}`,
    BGEZAL: (fields, pc) => `bgezal\t${Registers[fields.rs]}, $${((pc + 4) + (fields.simm16 * 4)).toString(16)}`,

    SYSCALL: (fields, pc) => `syscall\t$${fields.imm20.toString(16)}`,
    BREAK: (fields, pc) => `break\t$${fields.imm20.toString(16)}`,

    MFC0: (fields, pc) => `mfc0\t${Registers[fields.rt]}, ${COP0Registers[fields.rd]}`,
    MTC0: (fields, pc) => `mtc0\t${Registers[fields.rt]}, ${COP0Registers[fields.rd]}`,
    RFE: (fields, pc) => `cop0\trte`,
    TLBR: (fields, pc) => `cop0\ttlbr`,
    TLBWI: (fields, pc) => `cop0\ttlbwi`,
    TLBWR: (fields, pc) => `cop0\ttlbwr`,
    TLBP: (fields, pc) => `cop0\ttlbp`,
    CFC0: (fields, pc) => `cfc0\t${Registers[fields.rt]}, cop0cnt${fields.rd}`,
    CTC0: (fields, pc) => `ctc0\t${Registers[fields.rt]}, cop0cnt${fields.rd}`,
    LWC0: (fields, pc) => `lwc0\t${COP0Registers[fields.rt]}, ${fields.imm16}(${Registers[fields.rs]})`,
    SWC0: (fields, pc) => `swc0\t${COP0Registers[fields.rt]}, ${fields.imm16}(${Registers[fields.rs]})`
};
